import {createHmac,createHash,timingSafeEqual,randomBytes} from 'node:crypto';
import {validateContent} from '../../lib/content.mjs';
export const config={path:'/api/admin/:action',rateLimit:{action:'rate_limit',windowLimit:30,windowSize:60,aggregateBy:['ip','domain']}};
const cookieName='__Host-pd_admin';
const digest=x=>createHash('sha256').update(x).digest();
const equal=(a,b)=>timingSafeEqual(digest(a),digest(b));
const settings=()=>({password:process.env.ADMIN_PASSWORD,secret:process.env.ADMIN_SESSION_SECRET,token:process.env.GITHUB_TOKEN,repo:process.env.GITHUB_REPOSITORY,branch:process.env.GITHUB_BRANCH||'main',origin:process.env.ADMIN_SITE_ORIGIN||process.env.URL});
const configured=s=>s.password?.length>=16&&s.secret?.length>=32&&s.token&&/^[\w.-]+\/[\w.-]+$/.test(s.repo||'')&&/^https:\/\//.test(s.origin||'');
const sign=(value,s)=>createHmac('sha256',s.secret).update(value).digest('base64url');
export const sessionToken=s=>{const value=Buffer.from(JSON.stringify({exp:Date.now()+3600000,nonce:randomBytes(16).toString('hex'),version:digest(s.password).toString('hex')})).toString('base64url');return value+'.'+sign(value,s);};
export function authenticated(req,s){try{const cookie=(req.headers.get('cookie')||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(cookieName+'='));if(!cookie)return false;const [value,signature]=cookie.slice(cookieName.length+1).split('.');if(!value||!signature||!equal(signature,sign(value,s)))return false;const claims=JSON.parse(Buffer.from(value,'base64url').toString());return claims.exp>Date.now()&&claims.exp<Date.now()+3600001&&equal(claims.version||'',digest(s.password).toString('hex'));}catch{return false;}}
const response=(data,status=200,headers={})=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});
class ApiError extends Error{constructor(message,status=400){super(message);this.status=status;}}
async function body(req,max=300000){const declared=Number(req.headers.get('content-length'));if(declared>max)throw new ApiError('El archivo excede el tamaño permitido.',413);const raw=await req.text();if(Buffer.byteLength(raw)>max)throw new ApiError('El archivo excede el tamaño permitido.',413);try{return JSON.parse(raw);}catch{throw new ApiError('Solicitud inválida.');}}
async function github(s,file,method='GET',payload){const suffix=method==='GET'?'?ref='+encodeURIComponent(s.branch):'';const url=`https://api.github.com/repos/${s.repo}/contents/${file}${suffix}`;const result=await fetch(url,{method,headers:{Authorization:`Bearer ${s.token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json','User-Agent':'PublicityDesign-Admin'},body:payload?JSON.stringify(payload):undefined,signal:AbortSignal.timeout(15000)});if(!result.ok){if(result.status===409||result.status===422)throw new ApiError('El contenido cambió o el archivo ya existe. Recarga el panel antes de guardar.',409);throw new ApiError('No se pudo acceder al repositorio. Revisa la conexión de GitHub en Netlify.',502);}return result.json();}
export default async function handler(req){
 const s=settings();if(!configured(s))return response({error:'El administrador aún no está activado. Configura la conexión de GitHub y las claves de acceso en Netlify.'},503);
 const action=new URL(req.url).pathname.split('/').pop();
 if(req.method!=='GET'){let expected;try{expected=new URL(s.origin).origin;}catch{return response({error:'Configuración de dominio inválida.'},503);}if(req.headers.get('origin')!==expected||req.headers.get('x-pd-admin')!=='1'||!req.headers.get('content-type')?.startsWith('application/json'))return response({error:'Solicitud no autorizada.'},403);}
 try{
  if(action==='login'&&req.method==='POST'){const input=await body(req,2000);if(typeof input.password!=='string'||!equal(input.password,s.password))return response({error:'Contraseña incorrecta.'},401);return response({ok:true},200,{'Set-Cookie':`${cookieName}=${sessionToken(s)}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=3600`});}
  if(action==='logout'&&req.method==='POST')return response({ok:true},200,{'Set-Cookie':`${cookieName}=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0`});
  if(!authenticated(req,s))return response({error:'Inicia sesión para continuar.'},401);
  if(action==='content'&&req.method==='GET'){const file=await github(s,'public/content.json');return response({content:JSON.parse(Buffer.from(file.content,'base64').toString('utf8')),sha:file.sha});}
  if(action==='content'&&req.method==='PUT'){const input=await body(req);try{validateContent(input.content);}catch(e){throw new ApiError(e.message);}if(!/^[a-f0-9]{40}$/.test(input.sha||''))throw new ApiError('Recarga el contenido antes de guardar.');const result=await github(s,'public/content.json','PUT',{message:'Actualizar contenido desde el administrador',content:Buffer.from(JSON.stringify(input.content,null,2)+'\n').toString('base64'),sha:input.sha,branch:s.branch});return response({ok:true,sha:result.content.sha,message:'Cambios guardados. Netlify publicará la nueva versión cuando termine el despliegue.'});}
  if(action==='upload'&&req.method==='POST'){const input=await body(req,4400000);if(typeof input.content!=='string'||!/^[A-Za-z0-9+/]+={0,2}$/.test(input.content))throw new ApiError('Archivo inválido.');const bytes=Buffer.from(input.content,'base64');if(bytes.length>3000000||bytes.length<12)throw new ApiError('El tamaño máximo de archivo es 3 MB.',413);let ext;if(bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP')ext='webp';else if(bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))ext='png';else if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)ext='jpg';else if(bytes.subarray(4,8).toString()==='ftyp'&&bytes.subarray(8,12).toString().match(/^(isom|mp4[12]|avc1|M4V |iso[2-6])/))ext='mp4';else throw new ApiError('Usa una imagen PNG, JPG o WebP, o un video MP4.');const name=`upload-${Date.now()}-${randomBytes(6).toString('hex')}.${ext}`;await github(s,'public/assets/'+name,'PUT',{message:'Añadir material desde el administrador',content:bytes.toString('base64'),branch:s.branch});return response({url:'/assets/'+name});}
  return response({error:'Ruta o método no disponible.'},405);
 }catch(e){if(e instanceof ApiError)return response({error:e.message},e.status);return response({error:'No pudimos completar la operación. Intenta nuevamente.'},502);}
}
