import test,{afterEach} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import handler,{sessionToken,authenticated} from '../netlify/functions/admin.mjs';
import {validateContent} from '../lib/content.mjs';
const content=JSON.parse(fs.readFileSync(new URL('../public/content.json',import.meta.url)));
const originalFetch=globalThis.fetch;
const envKeys=['ADMIN_PASSWORD','ADMIN_SESSION_SECRET','GITHUB_TOKEN','GITHUB_REPOSITORY','GITHUB_BRANCH','ADMIN_SITE_ORIGIN'];
const envValues=Object.fromEntries(envKeys.map(k=>[k,process.env[k]]));
afterEach(()=>{globalThis.fetch=originalFetch;for(const[k,v]of Object.entries(envValues))if(v===undefined)delete process.env[k];else process.env[k]=v;});
function setup(){process.env.ADMIN_PASSWORD='example-strong-test-password';process.env.ADMIN_SESSION_SECRET='0123456789abcdef0123456789abcdef';process.env.GITHUB_TOKEN='test-token';process.env.GITHUB_REPOSITORY='example/publicity-design';process.env.GITHUB_BRANCH='main';process.env.ADMIN_SITE_ORIGIN='https://example.netlify.app';return {password:process.env.ADMIN_PASSWORD,secret:process.env.ADMIN_SESSION_SECRET};}
function request(action,method='GET',body,token){return new Request('https://example.netlify.app/api/admin/'+action,{method,headers:{Origin:'https://example.netlify.app','X-PD-Admin':'1','Content-Type':'application/json',...(token?{Cookie:'__Host-pd_admin='+token}:{})},body:body?JSON.stringify(body):undefined});}
test('original content and all portfolio metrics are valid',()=>{assert.equal(validateContent(content),content);assert.equal(content.projects.filter(p=>p.category==='videos').reduce((s,p)=>s+p.views,0),1366700);});
test('rejects unsafe media URLs and duplicate project ids',()=>{const d=structuredClone(content);d.projects[0].src='javascript:alert(1)';assert.throws(()=>validateContent(d));d.projects[0].src='/assets/../admin/index.html';assert.throws(()=>validateContent(d));d.projects[0].src='/assets/gang-nam.mp4';d.projects[1].id=d.projects[0].id;assert.throws(()=>validateContent(d));});
test('rejects missing contact and negative metrics',()=>{const d=structuredClone(content);d.contact.whatsapp='';assert.throws(()=>validateContent(d));d.contact.whatsapp='59164474763';d.projects[0].views=-1;assert.throws(()=>validateContent(d));});
test('disabled configuration fails closed',async()=>{setup();delete process.env.GITHUB_TOKEN;const r=await handler(request('content'));assert.equal(r.status,503);});
test('anonymous content reads are rejected',async()=>{setup();globalThis.fetch=()=>{throw Error('must not call GitHub');};assert.equal((await handler(request('content'))).status,401);});
test('login verifies password and sets an HttpOnly secure session',async()=>{setup();assert.equal((await handler(request('login','POST',{password:'wrong'}))).status,401);const r=await handler(request('login','POST',{password:process.env.ADMIN_PASSWORD}));assert.equal(r.status,200);const cookie=r.headers.get('set-cookie');assert.match(cookie,/HttpOnly; Secure; SameSite=Strict/);assert.match(cookie,/__Host-pd_admin=/);});
test('signed sessions reject tampering and password changes',()=>{const s=setup(),token=sessionToken(s);assert.equal(authenticated(request('content','GET',null,token),s),true);assert.equal(authenticated(request('content','GET',null,token+'x'),s),false);assert.equal(authenticated(request('content','GET',null,token),{...s,password:'other-strong-password'}),false);});
test('expired sessions are rejected',()=>{const s=setup(),now=Date.now,token=sessionToken(s);try{Date.now=()=>now()+3601000;assert.equal(authenticated(request('content','GET',null,token),s),false);}finally{Date.now=now;}});
test('cross-origin saves are blocked',async()=>{const s=setup(),req=request('content','PUT',{content,sha:'a'.repeat(40)},sessionToken(s));req.headers.set('origin','https://attacker.example');assert.equal((await handler(req)).status,403);});
test('authorized save persists exact content using the current SHA',async()=>{const s=setup(),token=sessionToken(s);let captured;globalThis.fetch=async(url,opts)=>{captured={url,opts};return Response.json({content:{sha:'b'.repeat(40)}});};const r=await handler(request('content','PUT',{content,sha:'a'.repeat(40)},token));assert.equal(r.status,200);const payload=JSON.parse(captured.opts.body);assert.equal(payload.sha,'a'.repeat(40));assert.equal(payload.branch,'main');assert.deepEqual(JSON.parse(Buffer.from(payload.content,'base64')),content);assert.match(captured.url,/public\/content.json$/);});
test('conflicting edits return a useful error without overwriting',async()=>{const s=setup();globalThis.fetch=async()=>Response.json({}, {status:409});const r=await handler(request('content','PUT',{content,sha:'a'.repeat(40)},sessionToken(s)));assert.equal(r.status,409);});
test('unsafe uploads cannot create executable files',async()=>{const s=setup();const r=await handler(request('upload','POST',{content:Buffer.from('<script>alert(1)</script>').toString('base64')},sessionToken(s)));assert.equal(r.status,400);});
test('image uploads use server-generated safe file paths',async()=>{const s=setup();let written;globalThis.fetch=async(url,opts)=>{written={url,payload:JSON.parse(opts.body)};return Response.json({content:{}});};const bytes=Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),Buffer.alloc(20)]);const r=await handler(request('upload','POST',{content:bytes.toString('base64'),name:'../../evil.mjs'},sessionToken(s)));assert.equal(r.status,200);assert.match((await r.json()).url,/^\/assets\/upload-\d+-[a-f0-9]+\.png$/);assert.match(written.url,/public\/assets\/upload-/);});
